import "./globals.css";
import type { Metadata } from "next";
// import { Nunito } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

// const nunito = Nunito({
//   weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
//   style: ["normal", "italic"],
//   subsets: ["cyrillic", "latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      // className={nunito.className}
      >
        <header className="bg-gradient-to-r from-blue-200 via-blue-400 to-purple-700 h-20 transition-all">
          <div className="container mx-auto flex justify-around items-center py-4 uppercase">
            <Link href="/">
              <Image
                src="/logo.svg"
                alt="Instagram Logo"
                className="pointer"
                width={140}
                height={40}
                priority
              />
            </Link>

            <nav className="flex gap-4 text-black">
              <Link href="/" className=" hover:text-pink-300">
                inicio
              </Link>
              <Link href="/nosotros" className="hover:text-pink-300">
                nosotros
              </Link>
              <Link href="/conectate" className="hover:text-pink-300">
                contactate
              </Link>
              <Link href="/blog" className="hover:text-pink-300">
                blog
              </Link>
              <Link href="/contacto" className="hover:text-pink-300">
                contacto
              </Link>

              <a href="" target="_blank" className="hover:text-gray-200 w-6">
                <Image
                  src="/instagram.svg"
                  alt="Instagram Logo"
                  width={22}
                  height={22}
                  priority
                />
              </a>

              <a href="" target="_blank" className="hover:text-gray-200">
                <Image
                  src="/linkedin.svg"
                  alt="Linkedin Logo"
                  width={22}
                  height={22}
                  priority
                />
              </a>

              <a href="" target="_blank" className="hover:text-gray-200">
                <Image
                  src="/twitter.svg"
                  alt="twitter Logo"
                  width={22}
                  height={22}
                  priority
                />
              </a>

              <a href="" target="_blank" className="hover:text-gray-200">
                <Image
                  src="/facebook.svg"
                  alt="facebook Logo"
                  width={22}
                  height={22}
                  priority
                />
              </a>
            </nav>
          </div>
        </header>

        {children}

        <footer className="max-w-screen-xl mx-auto py-8 px-4 ">
          <div className="flex justify-between gap-6">
            <div className="text-center md:text-left">
              <div className="text-xl font-bold">
                <Image
                  src="/logo.svg"
                  alt="Instagram Logo"
                  className="pointer"
                  width={300}
                  height={90}
                  priority
                />
              </div>
            </div>

            <div className="flex justify-around gap-16">
              <div>
                <div className="text-xl font-bold">Website</div>
                <div className="flex flex-col">
                  <Link href="/" className=" hover:text-white">
                    inicio
                  </Link>
                  <Link href="/nosotros" className=" hover:text-white">
                    nosotros
                  </Link>
                  <Link href="/conectate" className=" hover:text-white">
                    contactate
                  </Link>
                  <Link href="/blog" className=" hover:text-white">
                    blog
                  </Link>
                  <Link href="/contacto" className=" hover:text-white">
                    contacto
                  </Link>
                </div>
              </div>

              <div className="text-center md:text-left">
                <div className="text-xl font-bold">Pronto</div>
                <div>
                  <div className="">Blog</div>
                  <div className="">Escuela conecta</div>
                  <div className="">Bootcamp</div>
                </div>
              </div>

              <div className="text-center md:text-left">
                <div className="text-xl font-bold">Aliados</div>
                <a
                  href="https://www.iopenerinstitute.com/happiness-at-work-what"
                  className=" hover:text-white"
                >
                  i Opener Institute
                </a>
              </div>
            </div>

            <div className="text-center md:text-left">
              <div className="text-xl font-bold">Contacto</div>
              <div>
                <div>
                  {/* <img src="/path/to/img" alt="icon" className="h-6" /> */}
                  <div className="">info@conectatuproposito.com</div>
                </div>
                <div>
                  {/* <img src="/path/to/img" alt="icon" className="h-6" /> */}
                  <div className="">(+57) 310 767 52 03</div>
                </div>
                <div>
                  {/* <img src="/path/to/img" alt="icon" className="h-6" /> */}
                  <div className="">Envigado - Colombia</div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-8 flex flex-col md:flex-row justify-between items-center">
            <div></div>
            <div></div>

            <div className="text-center md:text-left">
              <div className="">
                Registráte para obtener beneficios y contenido de valor
              </div>
              <div className="mt-4 flex items-center">
                <input
                  type="text"
                  className="bg-gray-700  py-2 px-4 rounded-lg focus:outline-none"
                  placeholder="Ingresa tu correo electrónico"
                />
                <button className="ml-2 bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600 focus:outline-none">
                  Suscribir
                </button>
              </div>
            </div>

            <div className="mt-8 md:mt-0">
              <div className="">Síguenos en redes sociales</div>
              <div className="mt-2 flex space-x-2">
                <a href="" target="_blank" className=" hover:text-white">
                  instagram
                </a>
                <a href="" target="_blank" className=" hover:text-white">
                  linkedin
                </a>
                <a href="" target="_blank" className=" hover:text-white">
                  twitter
                </a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
