import "./globals.css";
import type { Metadata } from "next";
// import { Nunito } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

// const nunito = Nunito({
//   weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
//   style: ["normal", "italic"],
//   subsets: ["cyrillic", "latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      // className={nunito.className}
      >
        <Header />

        <main>{children}</main>

        <Footer />

        <div className="flex items-center justify-center h-20 w-full  bg-gradient-to-r from-blue-200 via-blue-400 to-purple-700">
          ©2023 Conecta tu propósito. All rights reserved
        </div>
      </body>
    </html>
  );
}
